### ISSUE TITLE
Include all GPS sensor readings

### ISSUE THREAD

**Issue by giakhanh780f** [mi3nts/mints-air-quality-live-web#14]
As of this posting, the car itself may not be displayed on the map due to site pulling from only one GPS sensor. There are multiple other GPS sensors on the car that can be utilized, the list is below:

- 001e0610c2e7/GPSGPGGA1
- 001e0610c2e7/GPSGPGGA2
- 001e0610c2e7/GPSGPGGA3
- 001e0610c2e7/GPSGPRMC1
- 001e0610c2e7/GPSGPRMC2
- 001e0610c2e7/GPSGPRMC3

Implement reading from all of these sensors and average out their data for display on the map.

Sidenote: To see whether the car is transmitting, hide the SharedAir Monitors layer from the map sidebar. If you see nothing, either the car is not transmitting data or something went wrong with the GPS sensor being read from if you are only reading from one sensor (otherwise double-check your implementation and let me know if something is up).

**Comment by Kevin346** [comment]
Just finished writing code that appears would resolve this, I suppose we can review this solution and close this in the next meeting.
